// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMa0pWgh_96N7Sj-pUQAVF1_niW7OBc0',
    appId: '1:837322519755:web:205cdedff1480613efd74e',
    messagingSenderId: '837322519755',
    projectId: 'lakbyke-39f1f',
    authDomain: 'lakbyke-39f1f.firebaseapp.com',
    databaseURL: 'https://lakbyke-39f1f-default-rtdb.firebaseio.com',
    storageBucket: 'lakbyke-39f1f.firebasestorage.app',
    measurementId: 'G-GYEZT06E9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6y21J4v2uuCVvcVksIG4v6LAl_w3mMJU',
    appId: '1:837322519755:android:b59de0e9683052ddefd74e',
    messagingSenderId: '837322519755',
    projectId: 'lakbyke-39f1f',
    databaseURL: 'https://lakbyke-39f1f-default-rtdb.firebaseio.com',
    storageBucket: 'lakbyke-39f1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqrpPckb84D28uSEYjwtBy6z2JFSNvPUE',
    appId: '1:837322519755:ios:fb1a06a3d193d5d9efd74e',
    messagingSenderId: '837322519755',
    projectId: 'lakbyke-39f1f',
    databaseURL: 'https://lakbyke-39f1f-default-rtdb.firebaseio.com',
    storageBucket: 'lakbyke-39f1f.firebasestorage.app',
    androidClientId: '837322519755-g798gc3hu4rd15p5dglbavsj9lg77alr.apps.googleusercontent.com',
    iosClientId: '837322519755-is4v2srtssi2ufhbddr33m7h2o5su625.apps.googleusercontent.com',
    iosBundleId: 'com.example.lakbykeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqrpPckb84D28uSEYjwtBy6z2JFSNvPUE',
    appId: '1:837322519755:ios:fb1a06a3d193d5d9efd74e',
    messagingSenderId: '837322519755',
    projectId: 'lakbyke-39f1f',
    databaseURL: 'https://lakbyke-39f1f-default-rtdb.firebaseio.com',
    storageBucket: 'lakbyke-39f1f.firebasestorage.app',
    androidClientId: '837322519755-g798gc3hu4rd15p5dglbavsj9lg77alr.apps.googleusercontent.com',
    iosClientId: '837322519755-is4v2srtssi2ufhbddr33m7h2o5su625.apps.googleusercontent.com',
    iosBundleId: 'com.example.lakbykeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMa0pWgh_96N7Sj-pUQAVF1_niW7OBc0',
    appId: '1:837322519755:web:205cdedff1480613efd74e',
    messagingSenderId: '837322519755',
    projectId: 'lakbyke-39f1f',
    authDomain: 'lakbyke-39f1f.firebaseapp.com',
    databaseURL: 'https://lakbyke-39f1f-default-rtdb.firebaseio.com',
    storageBucket: 'lakbyke-39f1f.firebasestorage.app',
    measurementId: 'G-GYEZT06E9M',
  );
}
