import 'package:flutter/material.dart';
import 'package:lakbyke_mobile/utils/theme.dart';
import 'package:lakbyke_mobile/screens/onboarding/onboarding_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was just generated by the CLI

Future<void> main() async {
  // 1. Initialize the Flutter engine first
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with the options for the current platform (Web/Android/iOS)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Run the app
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LakByke',
      theme: AppTheme.lightTheme,
      home: const OnboardingScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}